#!/bin/bash -eux
function main() {

  local scripts_dir
  scripts_dir=$(cd "$(dirname "${0}")" && pwd)

  local root_dir
  root_dir=$(cd "${scripts_dir}/.." && pwd)
  pushd "${root_dir}" > /dev/null
    go run github.com/onsi/ginkgo/v2/ginkgo \
      -v \
      -r \
      --race \
      --fail-fast \
      --randomize-all \
      --randomize-suites \
      --timeout=3h \
      "$@"
  popd > /dev/null
}

main "$@"
