#!/bin/bash -eux
function main() {

  local scripts_dir
  scripts_dir=$(cd "$(dirname "${0}")" && pwd)

  local root_dir
  root_dir=$(cd "${scripts_dir}/.." && pwd)
  pushd "${root_dir}" > /dev/null
    dep ensure
    export GO15VENDOREXPERIMENT=1
    go get github.com/onsi/ginkgo/ginkgo

    ginkgo \
      -v \
      -r \
      -race \
      -failFast \
      -succinct \
      -randomizeAllSpecs \
      -randomizeSuites \
      -slowSpecThreshold 300 \
      "$@"
  popd > /dev/null
}

main "$@"
