#!/bin/bash -eu

# We generally assume that postgres-ci-env is cloned to ../postgres-ci-env
SCRIPT_PATH=$(dirname $(realpath -s $0))

if [ $# -eq 0 ]; then
  echo "Error: Missing argument for which pipeline to destroy. Possible values are:"
  find ci/pipelines -name '*.yml' -exec basename {} .yml \;
  exit 1
fi

pipeline="${1}"

function grab() {
  local key=${1:?"Missing key to grab"}
  local deployment="${SCRIPT_PATH}/../../postgres-ci-env/deployments/concourse/concourse_v2.yml"
  grep "${key}" "${deployment}" | awk '{split($0,a,": "); print a[2]}'
}

function login() {
  fly \
      --target pgci \
    login  \
      --concourse-url=https://postgres.ci.cf-app.com/ \
      --username="$(grab basic_auth_username)" \
      --password="$(grab basic_auth_password)"
}

function destroy-pipeline(){
  fly \
      --target pgci \
    destroy-pipeline \
      --pipeline=$pipeline
}

function main(){
  login
  destroy-pipeline
}

main "${PWD}"
