jobs:
- name: bump-golang-dependencies
  serial_groups:
    - dependency-bumps
  plan:
    - in_parallel:
        - get: postgres-release
        - get: golang-release
        - get: golang-release-registry-image
        - get: weekly
          trigger: true
    - task: bump-deps
      file: golang-release/ci/tasks/shared/bump-deps.yml
      image: golang-release-registry-image
      input_mapping:
        input_repo: postgres-release
      output_mapping:
        output_repo: postgres-release
      params:
        SOURCE_PATH: src/acceptance-tests
    - put: postgres-release
      params:
        repository: postgres-release
        rebase: true

- name: bump-packages
  serial_groups:
    - dependency-bumps
  plan:
    - in_parallel:
        - get: bosh-cli-registry-image
        - get: postgres-release
        - get: postgres-13-src
          trigger: true
        - get: postgres-15-src
          trigger: true
        - get: postgres-16-src
          trigger: true
        - get: yq-release
          trigger: true
          params:
            globs:
              - yq_linux_amd64
    - task: bump-postgres-13-package
      file: postgres-release/ci/tasks/bump-postgres-packages/task.yml
      image: bosh-cli-registry-image
      input_mapping:
        postgres-src: postgres-13-src
      params:
        MAJOR_VERSION: 13
        PRIVATE_YML: |
          blobstore:
            options:
              access_key_id: ((postgres-release-blobstore-user.username))
              secret_access_key: ((postgres-release-blobstore-user.password))
    - task: bump-postgres-15-package
      file: postgres-release/ci/tasks/bump-postgres-packages/task.yml
      image: bosh-cli-registry-image
      input_mapping:
        postgres-src: postgres-15-src
      params:
        MAJOR_VERSION: 15
        PRIVATE_YML: |
          blobstore:
            options:
              access_key_id: ((postgres-release-blobstore-user.username))
              secret_access_key: ((postgres-release-blobstore-user.password))
    - task: bump-postgres-16-package
      file: postgres-release/ci/tasks/bump-postgres-packages/task.yml
      image: bosh-cli-registry-image
      input_mapping:
        postgres-src: postgres-16-src
      params:
        MAJOR_VERSION: 16
        PRIVATE_YML: |
          blobstore:
            options:
              access_key_id: ((postgres-release-blobstore-user.username))
              secret_access_key: ((postgres-release-blobstore-user.password))
    - task: bump-yq-package
      file: postgres-release/ci/tasks/bump-yq-packages/task.yml
      image: bosh-cli-registry-image
      params:
        PRIVATE_YML: |
          blobstore:
            options:
              access_key_id: ((postgres-release-blobstore-user.username))
              secret_access_key: ((postgres-release-blobstore-user.password))
    - put: postgres-release
      params:
        repository: postgres-release
        rebase: true

- name: run-acceptance-tests
  serial: true
  plan:
    - in_parallel:
        - get: bosh-warden-cpi-registry-image
        - get: postgres-release
          trigger: true
        - get: stemcell
          resource: warden-ubuntu-jammy-stemcell
          trigger: true
        - get: bbr-github-release
          params:
            globs:
              - bbr-*.tar
    - task: run-acceptance-tests
      file: postgres-release/ci/tasks/run-acceptance-tests/task.yml
      image: bosh-warden-cpi-registry-image
      privileged: true

- name: automatically-release-new-patch
  serial_groups:
    - version
  plan:
    - in_parallel:
        - get: postgres-release
          trigger: true
          passed:
            - run-acceptance-tests
        - get: current-version
          resource: version
        - get: patched-version
          resource: version
          params:
            bump: patch
        - get: bosh-shared-ci
        - get: bosh-security-scanner-registry-image
    - try:
        task: check-for-updated-blobs
        file: bosh-shared-ci/tasks/release/check-for-updated-blobs.yml
        image: bosh-security-scanner-registry-image
        input_mapping:
          input_repo: postgres-release
          version: current-version
        params:
          BLOBS:
            - postgresql-11
            - postgresql-13
            - postgresql-15
            - postgresql-16
            - yq
        on_success:
          do:
            - put: release-notes
              params:
                file: release-notes/release-notes.md
            - put: version
              params:
                file: patched-version/version
    - task: ensure-blob-update-checker-succeeded
      file: bosh-shared-ci/tasks/release/ensure-task-succeeded.yml
      image: bosh-security-scanner-registry-image
      input_mapping:
        task-output-folder: blob-updates

- name: create-final-release
  disable_manual_trigger: true
  serial_groups:
    - version
  plan:
    - in_parallel:
        - get: version
          trigger: true
        - get: bosh-cli-registry-image
        - get: postgres-release
          passed:
            - run-acceptance-tests
        - get: release-notes
        - get: bosh-shared-ci
    - task: create-final-release
      image: bosh-cli-registry-image
      file: bosh-shared-ci/tasks/release/create-final-release.yml
      input_mapping:
        release_repo: postgres-release
      params:
        GIT_USER_NAME: CI Bot
        GIT_USER_EMAIL: bots@cloudfoundry.org
        PRIVATE_YML: |
          blobstore:
            options:
              access_key_id: ((postgres-release-blobstore-user.username))
              secret_access_key: ((postgres-release-blobstore-user.password))
    - put: postgres-release
      no_get: true
      params:
        repository: release_repo
        tag: release_metadata/tag-name
    - put: postgres-github-release
      params:
        name: release_metadata/tag-name
        tag: release_metadata/tag-name
        body: release-notes/release-notes.md
        commitish: release_repo/.git/HEAD
        generate_release_notes: true
    - put: release-notes
      params:
        file: release_metadata/empty-file

- name: release-new-patch
  serial_groups:
    - version
  plan:
    - put: version
      params:
        bump: patch

- name: release-new-minor
  serial_groups:
    - version
  plan:
    - put: version
      params:
        bump: minor

- name: release-new-major
  serial_groups:
    - version
  plan:
    - put: version
      params:
        bump: major

resources:
  - name: bbr-github-release
    type: github-release
    source:
      owner: cloudfoundry
      repository: bosh-backup-and-restore
      access_token: ((github_public_repo_token))

  - name: bosh-cli-registry-image
    type: registry-image
    source:
      repository: bosh/cli
      username: ((dockerhub_username))
      password: ((dockerhub_password))

  - name: bosh-warden-cpi-registry-image
    type: registry-image
    source:
      repository: bosh/warden-cpi
      username: ((dockerhub_username))
      password: ((dockerhub_password))

  - name: bosh-security-scanner-registry-image
    type: registry-image
    source:
      repository: bosh/security-scanner
      username: ((dockerhub_username))
      password: ((dockerhub_password))

  - name: golang-release-registry-image
    type: registry-image
    source:
      repository: bosh/golang-release
      username: ((dockerhub_username))
      password: ((dockerhub_password))

  - name: bosh-shared-ci
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-shared-ci.git
      private_key: ((github_deploy_key_bosh-shared-ci.private_key))

  - name: golang-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-package-golang-release.git

  - name: postgres-13-src
    type: http-resource
    source:
      index: "https://ftp.postgresql.org/pub/source/"
      regex: 'href="v(?P<version>13\.[0-9.]+)/"'
      uri: "https://ftp.postgresql.org/pub/source/v{version}/postgresql-{version}.tar.gz"

  - name: postgres-15-src
    type: http-resource
    source:
      index: "https://ftp.postgresql.org/pub/source/"
      regex: 'href="v(?P<version>15\.[0-9.]+)/"'
      uri: "https://ftp.postgresql.org/pub/source/v{version}/postgresql-{version}.tar.gz"

  - name: postgres-16-src
    type: http-resource
    source:
      index: "https://ftp.postgresql.org/pub/source/"
      regex: 'href="v(?P<version>16\.[0-9.]+)/"'
      uri: "https://ftp.postgresql.org/pub/source/v{version}/postgresql-{version}.tar.gz"

  - name: yq-release
    type: github-release
    source:
      owner: mikefarah
      repository: yq
      tag_filter: v(4\.[0-9.]+)

  - name: postgres-release
    type: git
    source:
      uri: git@github.com:cloudfoundry/postgres-release.git
      branch: main
      private_key: ((github_deploy_key_postgres-release.private_key))

  - name: postgres-github-release
    type: github-release
    source:
      owner: cloudfoundry
      repository: postgres-release
      access_token: ((github_public_repo_token))

  - name: warden-ubuntu-jammy-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-jammy-go_agent

  - name: weekly
    type: time
    source:
      start: 3:00
      stop: 4:30
      days: [ Saturday ]

  - name: release-notes
    type: gcs-resource
    source:
      bucket: postgres-release-pipeline
      json_key: ((gcp_json_key))
      versioned_file: release-notes.md

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:cloudfoundry/postgres-release.git
      branch: release-semver
      file: VERSION
      private_key: ((github_deploy_key_postgres-release.private_key))

resource_types:
  - name: http-resource
    type: registry-image
    source:
      repository: aequitas/http-resource
      username: ((dockerhub_username))
      password: ((dockerhub_password))

  - name: gcs-resource
    type: registry-image
    source:
      repository: frodenas/gcs-resource
      username: ((dockerhub_username))
      password: ((dockerhub_password))
